k2/k2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('progress_app.urls')),
    path('api/v1/', include('progress_app.api.urls')),
]

k2/progress_app/api/urls.py
"""
urls.py
"""
from django.urls import path, include
from progress_app.api import views

urlpatterns = [
    path("progress_app/user/", views.UserList.as_view()),
    path("progress_app/user/<int:pk>/", views.UserDetail.as_view()),
    path(
        "progress_app/progress-report/", views.ProgressReportListCreateAPIView.as_view()
    ),
    # path("progress_app/progress-report/<int:pk>/", views.ProgressReportDetailCreateAPIView.as_view()),
    path(
        "progress_app/progress-report/<slug:slug>/",
        views.ProgressReportDetailCreateAPIView.as_view(),
    ),
    path(
        "progress_app/overall-progress/",
        views.OverallProgressAPIView.as_view(),
        name="overall_progress_api",
    ),
    path(
        "progress_app/overall-progress/<slug:slug>/",
        views.OverallProgressDetailAPIView.as_view(),
    ),
    path("api-auth/", include("rest_framework.urls")),
]

k2/progress_app/urls.py
"""this is url for the progress_app"""

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    CustomLoginView,
    CustomLogoutView,
    UpdateProgressReportView,
    AttendanceReportView,
    MarksheetView,
    AssignmentReportView,
    OverallProgressView,
    StudentDetailView,
)

app_name = "progress_app"

urlpatterns = [
    path("", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path(
        "update_progress_report/<int:pk>/",
        UpdateProgressReportView.as_view(),
        name="update_progress_report",
    ),
    path("progress_graph/", AttendanceReportView.as_view(), name="progress_graph"),
    path("marksheet/", MarksheetView.as_view(), name="marksheet"),
    path(
        "assignment_report/", AssignmentReportView.as_view(), name="assignment_report"
    ),
    path("overall_progress/", OverallProgressView.as_view(), name="overall_progress"),
    path(
        "student_detail/<str:username>/",
        StudentDetailView.as_view(),
        name="student_detail",
    ),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

k2/progress_app/models.py
"""this is Django ORM model"""

from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import Avg
from django.utils.text import slugify


class ProgressReport(models.Model):
    """this is model for Progress report of User"""

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    week_number = models.PositiveIntegerField()
    attendance = models.PositiveIntegerField()
    assignment = models.PositiveIntegerField()
    marks = models.PositiveIntegerField()
    comments = models.TextField()
    slug = models.SlugField(unique=True, max_length=255, blank=True)



    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug =  f"{self.user.username}--agk"
            unique_slug = base_slug
            counter = 1

            while ProgressReport.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{counter}-agk"
                counter += 1

            self.slug = unique_slug

        super().save(*args, **kwargs)


    def get_trainee_attendance(self, progress_reports):
        """To get the trainee's assignment data"""
        all_users = [
            report.user for report in progress_reports if not report.user.is_superuser
        ]

        attendance_data = {}
        for user in all_users:
            progress_reports = ProgressReport.objects.filter(user=user)
            percentages = [report.attendance / 100.0 for report in progress_reports]
            attendance_data[user.username] = percentages

        return attendance_data

    def get_trainee_marks(self, progress_reports):
        """To get the trainee's assignment data"""
        all_users = [
            report.user for report in progress_reports if not report.user.is_superuser
        ]

        mark_data = {}
        for user in all_users:
            user_reports = ProgressReport.objects.filter(user=user)
            marks = [report.marks / 100.0 for report in user_reports]
            mark_data[user.username] = marks

        return mark_data

    def get_trainee_assignment(self, progress_reports):
        """To get the trainee's assignment data"""
        all_users = [
            report.user for report in progress_reports if not report.user.is_superuser
        ]

        assignment_data = {}
        for user in all_users:
            user_reports = ProgressReport.objects.filter(user=user)
            assignments = [report.assignment / 100.0 for report in user_reports]
            assignment_data[user.username] = assignments

        return assignment_data

    @classmethod
    def get_trainee_overall_score(cls, progress_reports):
        """to get the trainee's overall data"""
        # all_users = User.objects.filter(is_superuser=False)
        all_users = [
            report.user for report in progress_reports if not report.user.is_superuser
        ]
        overall_data = {}
        for user in all_users:
            progress_reports = ProgressReport.objects.filter(user=user)

            if progress_reports:
                attendance_aggregate = progress_reports.aggregate(
                    average=Avg("attendance")
                )
                average_attendance = attendance_aggregate["average"]
                attendance_percentage = average_attendance / 100.0
            else:
                attendance_percentage = 0

            if progress_reports:
                marks_aggregate = progress_reports.aggregate(average=Avg("marks"))
                average_marks = marks_aggregate["average"]
                marks_percentage = average_marks / 100.0
            else:
                marks_percentage = 0

            if progress_reports:
                assignment_aggregate = progress_reports.aggregate(
                    average=Avg("assignment")
                )
                average_assignment = assignment_aggregate["average"]
                assignment_percentage = average_assignment / 100.0
            else:
                assignment_percentage = 0

            overall_data[user.username] = (
                attendance_percentage + marks_percentage + assignment_percentage
            ) / 3

        return overall_data

k2/progress_app/forms.py
"""
forms.py
"""

from django import forms
from .models import ProgressReport


class ProgressReportForm(forms.ModelForm):
    """
    form to add marks and comments
    """

    class Meta:
        model = ProgressReport
        fields = ["marks", "comments"]

        widgets = {
            "marks": forms.NumberInput(attrs={"class": "form-control"}),
            "comments": forms.Textarea(attrs={"class": "form-control"}),
        }

k2/progress_app/api/views.py
"""
views.py
"""
from django.contrib.auth.models import User
from rest_framework import generics
from .serializers import USerSerializer, ProgressReportSerializer
from progress_app.models import ProgressReport
from rest_framework.pagination import LimitOffsetPagination
from .serializers import OverallProgressSerializer
from rest_framework.response import Response
from rest_framework import status


class UserList(generics.ListAPIView):
    """
    API view for listing and creating Book objects.
    """

    queryset = User.objects.all()
    serializer_class = USerSerializer


class UserDetail(generics.RetrieveAPIView):
    """
    API view for retrieving, updating, and deleting a Book object.
    """

    queryset = User.objects.all()
    serializer_class = USerSerializer


class ProgressReportListCreateAPIView(generics.ListCreateAPIView):
    """
    API view for listing and creating a ProgressReport object.
    """

    queryset = ProgressReport.objects.all()
    serializer_class = ProgressReportSerializer


class ProgressReportDetailCreateAPIView(generics.RetrieveUpdateDestroyAPIView):
    """
    API view for retrieving, updating, and deleting a ProgressReport object.
    """

    queryset = ProgressReport.objects.all()
    serializer_class = ProgressReportSerializer
    lookup_field = "slug"


class MyPagination(LimitOffsetPagination):
    """
    For Pagination
    """

    default_limit = 100
    max_limit = 10


class OverallProgressAPIView(generics.ListAPIView):
    """
    API view for listing and creating a Overall Progress object.
    """

    serializer_class = OverallProgressSerializer
    pagination_class = MyPagination

    def get_queryset(self):
        """
        to write queryset
        """
        return ProgressReport.objects.all()

    def list(self, request, *args, **kwargs):
        """
        to calulate dynamically Overall Progress
        """
        queryset = self.get_queryset()
        page = self.paginate_queryset(queryset)

        overall_data = ProgressReport.get_trainee_overall_score(page)
        serialized_data = []

        for username, overall_percentage in overall_data.items():
            serialized_data.append(
                {
                    "username": username,
                    "overall_percentage": overall_percentage * 100,
                }
            )

        serializer = self.get_serializer(data=serialized_data, many=True)
        serializer.is_valid()

        return self.get_paginated_response(serializer.data)

class OverallProgressDetailAPIView(generics.RetrieveAPIView):
    """
    API view to retrieve and retrieve Overall Progress object.
    """

    serializer_class = OverallProgressSerializer
    pagination_class = MyPagination
    lookup_field = "slug"

    def get_queryset(self):
        """
        to write queryset
        """
        return ProgressReport.objects.all()

    def retrieve(self, request, *args, **kwargs):
        """
        to retrieve Overall Progress
        """
        instance = self.get_object()
        overall_data = ProgressReport.get_trainee_overall_score([instance])
        username = instance.user.username

        if username in overall_data:
            serialized_data = {
                "username": username,
                "overall_percentage": overall_data[username] * 100,
            }

            serializer = self.get_serializer(data=serialized_data)
            serializer.is_valid()

            return Response(serializer.data, status=status.HTTP_200_OK)
        
        return Response({"detail": "User not found in overall data"})

k2/progress_app/views.py
"""this is view for progress_app"""

from django.contrib.auth import login
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DetailView, ListView
from django.http import Http404
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from progress_app.models import ProgressReport
from .forms import ProgressReportForm


class CustomLoginView(LoginView):
    "This class is used for login"
    template_name = "progress_app/login.html"

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return redirect(reverse_lazy("progress_app:overall_progress"))


class CustomLogoutView(LogoutView):
    """this is to logout"""

    next_page = reverse_lazy("progress_app:login")


class UpdateProgressReportView(UpdateView):
    """this is to update the Students marks and comments"""

    model = ProgressReport
    form_class = ProgressReportForm
    template_name = "progress_app/update_progress_report.html"
    login_url = reverse_lazy("progress_app:login")

    def get_object(self, queryset=None):
        progress_report_id = self.kwargs.get("pk", None)
        progress_report = get_object_or_404(ProgressReport, id=progress_report_id)
        return progress_report

    def get_success_url(self):
        return reverse_lazy(
            "progress_app:student_detail",
            kwargs={"username": self.object.user.username},
        )


class StudentDetailView(LoginRequiredMixin, DetailView):
    """this shows the detailed view of a single student's progress
    which includes attendance, marksgiven by mentor, assignment and comments given by mentor
    """

    User = get_user_model()
    model = User
    template_name = "progress_app/student_detail.html"
    login_url = reverse_lazy("progress_app:login")
    context_object_name = "user"
    paginate_by = 8

    def get_object(self, queryset=None):
        user_model = get_user_model()
        username = self.kwargs.get("username", None)
        users = user_model.objects.filter(username=username)

        if not users.exists():
            raise Http404("User not found")

        return users.first()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        progress_reports = ProgressReport.objects.filter(user=self.object)
        paginator = Paginator(progress_reports, self.paginate_by)
        page = self.request.GET.get("page")
        try:
            progress_reports_page = paginator.page(page)
        except PageNotAnInteger:
            progress_reports_page = paginator.page(1)
        except EmptyPage:
            progress_reports_page = paginator.page(paginator.num_pages)

        context["progress_reports"] = progress_reports_page
        return context


class AttendanceReportView(LoginRequiredMixin, ListView):
    """This shows the assignment submission report in percentage"""

    model = ProgressReport
    template_name = "progress_app/common_progress.html"
    login_url = reverse_lazy("progress_app:login")
    paginate_by = 100

    def get_queryset(self):
        all_users = get_user_model().objects.filter(is_superuser=False)
        return ProgressReport.objects.filter(user__in=all_users)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["data_type"] = "Attendance"
        temp = ProgressReport().get_trainee_attendance(context["object_list"])
        context["overall_data"] = temp
        return context


class MarksheetView(LoginRequiredMixin, ListView):
    """This shows the assignment submission report in percentage"""

    model = ProgressReport
    template_name = "progress_app/common_progress.html"
    login_url = reverse_lazy("progress_app:login")
    paginate_by = 100

    def get_queryset(self):
        all_users = get_user_model().objects.filter(is_superuser=False)
        return ProgressReport.objects.filter(user__in=all_users)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["data_type"] = "Marks"
        temp = ProgressReport().get_trainee_marks(context["object_list"])
        context["overall_data"] = temp
        return context


class AssignmentReportView(LoginRequiredMixin, ListView):
    """This shows the assignment submission report in percentage"""

    model = ProgressReport
    template_name = "progress_app/common_progress.html"
    login_url = reverse_lazy("progress_app:login")
    paginate_by = 100

    def get_queryset(self):
        all_users = get_user_model().objects.filter(is_superuser=False)
        return ProgressReport.objects.filter(user__in=all_users)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["data_type"] = "Assignment"
        temp = ProgressReport().get_trainee_assignment(context["object_list"])
        context["overall_data"] = temp
        return context


class OverallProgressView(LoginRequiredMixin, ListView):
    """This shows the overall progress of the student"""

    template_name = "progress_app/overall_progress.html"
    paginate_by = 100
    login_url = reverse_lazy("progress_app:login")
    model = ProgressReport

    def get_queryset(self):
        all_users = get_user_model().objects.filter(is_superuser=False)
        return ProgressReport.objects.filter(user__in=all_users)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        temp = ProgressReport().get_trainee_overall_score(context["object_list"])
        context["overall_data"] = temp
        return context

k2/progress_app/templates/progress_app/base.html
<html lang="en">
  {% load static %}
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>progress_app</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #7952b3;">
      <div class="container-fluid">
        <div class="navbar-brand">
          k2
          <img src="{% static '/progress_app/images/a.jpg' %}" alt="My image" style="height: 25px; width: 25px;" />
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/progress_graph/" style="color: white;">Attendance</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/assignment_report/" style="color: white;">Assignment</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/marksheet/" style="color: white;">Marks</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/overall_progress/" style="color: white;">Dashboard</a>
            </li>

            <li class="nav-item">
              <a class="btn btn-outline-dark" href="/logout/">logout <span class="sr-only"></span></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

k2/progress_app/templates/progress_app/common_progress.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <style>
      .green-box {
        width: 25px;
        height: 25px;
        background-color: green;
        border: 1px solid black;
        position: relative;
      }
      
      .tooltip-text {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        color: white;
        font-size: 14px;
        display: none;
      }
      
      .green-box:hover .tooltip-text {
        display: block;
      }
      
      .back-button {
        margin-top: 20px;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
      }
      
      .back-button:hover {
        background-color: #0056b3;
      }
    </style>
  </head>

  <body>
    {% extends 'progress_app/base.html' %}

    {% load static %}
    {% load custom_filters %}

    {% block content %}
      <div class="container mt-4">
        <h1>{{ data_type }}</h1>

        <div class="row my-5">
          {% for username, results in overall_data.items %}
            <div class="col-lg-3 col-md-4 col-12 d-flex justify-content-center align-items-center p-3">
              <div class="card" style="width: 18rem;">
                <div class="card-body height:12rem">
                  <h5 class="card-title">{{ username }}</h5>
                  <div class="row">
                    {% for result in results %}
                      <div class="col-3 d-flex justify-content-center align-items-center p-2">
                        <div class="green-box" style="opacity: {{ result|floatformat:2 }};" data-toggle="tooltip" data-placement="right" title="week:{{ forloop.counter }},{{ result|multiply_and_format_percentage }}%">
                          <div class="tooltip-text">{{ result|multiply_and_format_percentage }}</div>
                        </div>
                      </div>
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>

        <div class="pagination d-flex justify-content-center align-items-center">
          <span class="step-links">
            {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>

            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">next</a>
              <a href="?page={{ page_obj.num_pages }}">last &raquo;</a>
            {% endif %}
          </span>
        </div>
      </div>
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

k2/progress_app/templates/progress_app/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
  </head>
  <body>
    <div class="p-3 border border-dark">
      <h2>Login</h2>
      <form class="p-3" method="post" action="{% url 'progress_app:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
      </form>
    </div>
  </body>
</html>

k2/progress_app/templates/progress_app/overall_progress.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        .green-box {
            width: 25px;
            height: 25px;
            background-color: green;
            border: 1px solid black;
            position: relative;
        }

        .tooltip-text {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: white;
            font-size: 14px;
            display: none;
            
        }

        .green-box:hover .tooltip-text {
            display: block;
        }

        .back-button {
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }

        .back-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
    
    {% extends 'progress_app/base.html' %}
    {% load static %}
    {% load custom_filters %}
    {% block content %}

    <div class="container mt-4">
        <h1>Overall Progress</h1>
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Trainee</th>
                    <th scope="col">Overall</th>
                </tr>
            </thead>
            <tbody>
                <tbody>
                    {% for username,overall_average in overall_data.items %}
                    <tr>
                        <td>
                        <a href="{% url 'progress_app:student_detail' username=username %}">
                            {{ username }}
                        </a>
                    </td>
                    
                    <td>
                         <div class="green-box" style="opacity: {{overall_average }};" data-toggle="tooltip" data-placement="right" title="{{overall_average |multiply_and_format_percentage}}%">
                            <div class="tooltip-text">{{overall_average |multiply_and_format_percentage }}</div>
                        </div>
                    </td>                 
                    </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
    <br>
    <div class="pagination d-flex justify-content-center align-items-center">
        <span class="step-links">   
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>


    {% endblock %}

</body>

</html>

k2/progress_app/templates/progress_app/student_detail.html
{% extends 'progress_app/base.html' %}

{% block content %}
  <div class="dashboard-header p-3">
    <h3>{{ user.first_name }}'s Progress Report</h3>
  </div>

  <div class="row my-5">
    {% for progress_report in progress_reports %}
      <div class="col-lg-3 col-md-4 col-12 d-flex justify-content-center">
        <div class="card mb-5" style="width: 18rem;">
          <div class="card-header d-flex justify-content-between">
            <b>Week: {{ progress_report.week_number }}</b>
            <a href="{% url 'progress_app:update_progress_report' progress_report.pk %}" class="btn btn-outline-primary btn-sm">Update</a>
          </div>
          <div class="card-body">
            <li>Assignment: {{ progress_report.assignment }}%</li>
            <li>Attendance: {{ progress_report.attendance }}%</li>
            <li>Marks: {{ progress_report.marks }}</li>
            <li>Comments: {{ progress_report.comments }}</li>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="pagination d-flex justify-content-center align-items-center">
    <span class="step-links">
      {% if progress_reports.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ progress_reports.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">Page {{ progress_reports.number }} of {{ progress_reports.paginator.num_pages }}.</span>

      {% if progress_reports.has_next %}
        <a href="?page={{ progress_reports.next_page_number }}">next</a>
        <a href="?page={{ progress_reports.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
{% endblock %}

k2/progress_app/templates/progress_app/update_progress_report.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Update Progress Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
  </head>
  <body>
    {% extends 'progress_app/base.html' %}

    {% block content %}
      <div class="container mt-5">
        <div class="p-3 bg-light border rounded">
          <h2 class="mb-4">Update Progress Report</h2>
            <form method="post" action="{% url 'progress_app:update_progress_report' pk=object.pk %}">

            {% csrf_token %}
            <div class="mb-3 form-control">{{ form.as_p }}</div>
            <button type="submit" class="btn btn-primary">Save</button>
          </form>
        </div>
      </div>
    {% endblock %}
  </body>
</html>